# Validate generated license files on pull requests.
# This workflow intentionally does not auto-push into PR branches: PR code is untrusted.
name: License Check
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - ".github/licenses.tmpl"
      - "script/licenses*"
      - "third-party-licenses.*.md"
      - "third-party/**"

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR revision
        uses: actions/checkout@v7

      - name: Build UI
        uses: ./.github/actions/build-ui

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Regenerate licenses
        env:
          CI: "true"
        run: |
          export GOROOT=$(go env GOROOT)
          export PATH=${GOROOT}/bin:$PATH
          ./script/licenses

      - name: Verify generated license files are current
        run: script/licenses-check
